name: JavaForBukkit
version: '${version}'
main: br.dev.peixotim.javaforbukkit.JavaForBukkit
api-version: '1.20'

commands:
  hello:
    description: "Say Hello !"
    usage: /hello
  ping:
    description: "Return ping of user"
    usage: /myping
  site:
    description: "Displays the server's website."
    usage: /site
    aliases: ["website"]
  sum:
    description: "It adds two values."
    usage: /sum
  boots:
    description: "Grants the player who uses this command the glorious Hermes boots"
    usage: /boots
    aliases: ["/botas"]